plv1 = input()
plv2 = input()
plv3 = input()
plv4 = input()
plv5 = input()
plv6 = input()

plv1 = len(plv1)
plv2 = len(plv2)
plv3 = len(plv3)
plv4 = len(plv4)
plv5 = len(plv5)
plv6 = len(plv6)

print(f'{plv1}{plv2}{plv3}{plv4}{plv5}{plv6}')